global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fastapi
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'genai-coach-backend'
          environment: 'production'

remote_write:
  - url: https://prometheus-prod-26-prod-ap-south-0.grafana.net/api/prom/push
    basic_auth:
      username: '796842'
      password: ${GRAFANA_TOKEN}